(define (big-square x y z)
  (define xy (+ (* x x) (* y y)))
  (define xz (+ (* x x) (* z z)))
  (define yz (+ (* y y) (* z z)))
  (if (> xy xz) (if (> yz xy) yz xy) (if (> yz xz) yz xz))
)
(define test (= (big-square 1 2 3)
                (big-square 1 3 2)
                (big-square 2 1 3)
                (big-square 2 3 1)
                (big-square 3 1 2)
                (big-square 3 2 1)
                13 ))
